# Makefile for tb_decoder

include ../includes/tb_common.mk

TOP_MODULE = tb_decoder
RTL_SOURCES = ${RTL_DIR}/decoder.sv \
              ${RTL_DIR}/register_file.sv \
              ${RTL_DIR}/memory_inst.sv \
              ${RTL_DIR}/memory_data.sv