# Makefile for tb_datapath

include ../includes/tb_common.mk

BASE_DIR = ../..
TOP_MODULE = tb_datapath
RTL_SOURCES = ${RTL_DIR}/alu.sv \
              ${RTL_DIR}/comparator.sv \
              ${RTL_DIR}/decoder.sv \
              ${RTL_DIR}/register_file.sv \
              ${RTL_DIR}/datapath.sv \
              ${RTL_DIR}/datapath/datapath_pipelined.sv \
              ${RTL_DIR}/datapath/if_stage.sv \
              ${RTL_DIR}/datapath/id_stage.sv \
              ${RTL_DIR}/datapath/ex_stage.sv \
              ${RTL_DIR}/datapath/mem_stage.sv \
              ${RTL_DIR}/datapath/wb_stage.sv   \
              ${RTL_DIR}/unified_memory.sv  \
              ${RTL_DIR}/memory_request_sequencer.sv \
              ${RTL_DIR}/cache.sv   \
              ${RTL_DIR}/cache_fast.sv \
              ${RTL_DIR}/cache_request_if.sv \
              ${RTL_DIR}/mem_request_if.sv