# Makefile for tb_datapath

include ../includes/tb_common.mk

TOP_MODULE = tb_datapath
RTL_SOURCES = ${RTL_DIR}/alu.sv \
              ${RTL_DIR}/datapath.sv \
              ${RTL_DIR}/comparator.sv \
              ${RTL_DIR}/decoder.sv \
              ${RTL_DIR}/register_file.sv \
              ${RTL_DIR}/memory_inst.sv \
              ${RTL_DIR}/memory_data.sv