# Makefile for tb_datapath

include ../includes/tb_common.mk

BASE_DIR = ../..
TOP_MODULE = tb_datapath
RTL_SOURCES = ${RTL_DIR}/alu.sv \
              ${RTL_DIR}/comparator.sv \
              ${RTL_DIR}/decoder.sv \
              ${RTL_DIR}/register_file.sv \
              ${RTL_DIR}/memory_inst.sv \
              ${RTL_DIR}/memory_data.sv \
              ${RTL_DIR}/datapath.sv \
              ${RTL_DIR}/datapath/datapath_pipelined.sv \
              ${RTL_DIR}/datapath/if_stage.sv \
              ${RTL_DIR}/datapath/id_stage.sv \
              ${RTL_DIR}/datapath/ex_stage.sv \
              ${RTL_DIR}/datapath/mem_stage.sv \
              ${RTL_DIR}/datapath/wb_stage.sv