BASE_DIR = ../../..
include ../includes/tb_common.mk

TOP_MODULE = tb_store_buffer_frontend

RTL_SOURCES = \
	${RTL_DIR}/cache_request_if.sv \
	${RTL_DIR}/cache_writeonly_request_if.sv \
	${RTL_DIR}/mem_request_if.sv \
	${RTL_DIR}/store_buffer.sv \
	${RTL_DIR}/store_buffer_frontend.sv \
	${RTL_DIR}/cache_fast.sv \
	${RTL_DIR}/cache_readonly_request_if.sv \
	${RTL_DIR}/unified_memory.sv \
	${RTL_DIR}/memory_data.sv \
	${RTL_DIR}/memory_inst.sv \
	${RTL_DIR}/memory_request_sequencer.sv \
	${RTL_DIR}/cache_hit_query_if.sv