# Makefile for tb_reorder_buffer

include ../includes/tb_common.mk
BASE_DIR = ../../..
TOP_MODULE = tb_reorder_buffer
RTL_SOURCES = ${RTL_DIR}/reorder_buffer/reorder_buffer.sv \
              ${RTL_DIR}/reorder_buffer/rob_ticket_request_if.sv \
              ${RTL_DIR}/reorder_buffer/rob_reg_query_if.sv \
              ${RTL_DIR}/reorder_buffer/rob_store_query_if.sv
