BASE_DIR = ../..
include ../includes/tb_common.mk

TOP_MODULE = tb_cache

RTL_SOURCES = \
	${RTL_DIR}/cache_request_if.sv \
	${RTL_DIR}/mem_request_if.sv	\
	${RTL_DIR}/unified_memory.sv	\
	${RTL_DIR}/cache_fast.sv
# 	${RTL_DIR}/cache.sv
